### ISSUE TITLE
Fix unpack for certain environments

### ISSUE THREAD

**Issue by Tamnac** [jgm/djot.lua#15]
So, I don't really know lua really well.

But I've been using this library to make a plugin, but it errors out due to this line in a few places:

```lua
local unpack = unpack or table.unpack
```

It works if you change it to 
```lua
local unpack = table.unpack or unpack
```
I'm guessing cause short circuit eval

If that's an acceptable change I can open a pr for it

**Comment by jgm** [comment]
What error, exactly, are you getting?
`or` should short-circuit eval, so `unpack or table.unpack` should work fine if `unpack` is undefined.

**Comment by jgm** [comment]
The existing code should work fine. Look:
```
Lua 5.4.6  Copyright (C) 1994-2023 Lua.org, PUC-Rio
> unpack
nil
> unpack or table.unpack
function: 0x1033eade8
```

**Comment by jgm** [comment]
I'm not sure what "strict mode" is, but that's undoubtedly the source of the issue.  Anyway, I don't see any problem with the existing code, with either lua or luajit; it was designed to work with both.  Unless I know more about this issue, I'm not inclined to change anything.

**Comment by jgm** [comment]
> It turns out the env overrides the __index metamethod to throw an error instead of returning nil.

I've never heard of doing that.  The thing is, turning it around wouldn't really help.  The point of this statement is that luajit defines `unpack`, where lua has `table.unpack`.  So we handle them both.  If you flip the order as you're suggesting, you'd run into the same problem on luajit with a similar override on the __index metamethod.  So it's not really a principled solution.
