### ISSUE TITLE
MathML support

### ISSUE THREAD

**Issue by alterae** [jgm/djot.lua#18]
It appears that when generating HTML the inline and block equation syntaxes are outputting LaTeX-formatted text for use with MathJax, like so:

```djot
$$`e^{i \pi} - 1 = 0
```
```html
<p><span class="math display">\[e^{i \pi} - 1 = 0\]</span></p>
```

However, this introduces an external dependency on a javascript library to the document, which is not idea.

MathML is supported in all major browsers [according to MDN](https://developer.mozilla.org/en-US/docs/Web/MathML#browser_compatibility), and works in environments without javascript, allowing for smaller page sizes and better portability.

It would be nice to be able to output MathML in HTML documents.

**Comment by jgm** [comment]
`pandoc -f djot -t html --mathml` will do this.
Implementing MathML conversion in Lua would be a huge job -- not one I'm planning to undertake.

**Comment by alterae** [comment]
ahhh okay, that works

understandable! sorry to trouble you
