### ISSUE TITLE
JSON parse error: Error in $: JSON missing pandoc-api-version

### ISSUE THREAD

**Issue by gnusupport** [jgm/djot.lua#6]
When doing:

```
$ djot --ast --json my.dj |pandoc -f json -s -t html -o my.html
JSON parse error: Error in $: JSON missing pandoc-api-version.
```

**Comment by jgm** [comment]
djot.lua doesn't support creating a pandoc AST.
What you get with `--json` is rather a json version of the djot AST.
If you want to interoperate with pandoc, you can use either the custom pandoc reader in this repository or djot.js, which can emit pandoc JSON using `--pandoc`.

**Comment by gnusupport** [comment]
I have tried to follow, clearly wrongly, example as shown on https://djot.net website:

To convert a djot document to any format pandoc supports (in this example, docx):
```
$ djot -t pandoc mydoc.dj | pandoc -f json -s -t docx -o mydoc.docx
```

as `djot` now does not have `-t` option, what is the updated command line? In particular I would like to generate *PDF* file with it.

**Comment by jgm** [comment]
Those instructions are for the `djot` executable provided by djot.js, which you must install using the instructions on the website. They won't work for the `djot` provided by djot.lua. If you have both installed, make sure the `djot.js` version is firsrt in your PATH.
