### ISSUE TITLE
wrong markup for block elements?

### ISSUE THREAD

**Issue by ousia** [jgm/djot.lua#9]
@jgm,

I tried to add a class to a complete blockquote, such as in [the following sample](https://djot.net/playground/?text=_a_%7B.dz%7D%0A%0A%3E+%7B.a%7D%0A%3E%0A%3E+a%0A%3E%0A%3E+a%0A%3E%0A%3E+a%0A%3E%0A%3E+a&mode=html&sourcepos=false):

```
_a_{.dz}

> {.a}
>
> a
>
> a
>
> a
>
> a
```

But this only grants the class an an exclusive attribute to the first paragraph.

Is this really a a feature, or is it a bug?

Many thanks for your help.

**Comment by jgm** [comment]
You need to put the attribute in front of the element
```
{.a}
> a
>
> a
```
